version: '3'
services:
    api:
        build: .
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
        ports:
            - '8000:8000'
        restart: unless-stopped