name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: dokku-deploy
        uses: bakkacino/actions/dokku-deploy@main
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          dokku-host: ${{ secrets.DOKKU_HOST }}
          org-name: "bakkacino"
          app-name: "api"
          docker-registry: "registry.herjus.tech"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
